# Async & Performance ch3_0- promises 
---
author: Jason Song <metaseed@gmail.com>
version: 1.0.0
tag: [javascript]
subPage: []
enable: [toc]

---
*summery* 
## Promise API  

### new Promise(..) Constructor
```js
var p = new Promise( function(resolve,reject){
    // `resolve(..)` to fulfill or reject the promise: 
    //if passing in non-thenable/non-promise, fulfill; if passing thenable/promise, may reject correspondingly.
  
    // `reject(..)` to reject the promise
} );   

```  
`reject(..)` simply rejects the promise, but` resolve(..)` can either `fulfill` the promise or `reject` it, depending on what it's passed. If `resolve(..)` is passed an immediate, non-Promise, non-thenable value, then the promise is `fulfilled` with that value. But if `resolve(..)` is passed a genuine Promise or thenable value, that value is unwrapped recursively, and whatever its final resolution/state is will be adopted by the promise. 

A shortcut for creating an already-rejected Promise is `Promise.reject(..)`
, so these two promises are equivalent:

```js  
var p1 = new Promise( function(resolve,reject){
	reject( "Oops" );
} );

var p2 = Promise.reject( "Oops" );
```
`Promise.resolve(..)` also unwraps thenable values. In that case, the Promise returned adopts the final resolution of the thenable you passed in, which could either be fulfillment or rejection:

```js

var fulfilledTh = {
	then: function(cb) { cb( 42 ); }
};
var rejectedTh = {
    // thenable is an object with a `then` function that has 2 callback parameters.
	then: function(resolve, reject) {
		reject( "Oops" );
	}
};

// convert thenable to Promise
var p1 = Promise.resolve( fulfilledTh );
var p2 = Promise.resolve( rejectedTh );

// `p1` will be a fulfilled promise
// `p2` will be a rejected promise
```
And remember, `Promise.resolve(..)` doesn't do anything if what you pass is already a genuine Promise; it just returns the value directly. So there's no overhead to calling `Promise.resolve(..)` on values that you don't know the nature of, if one happens to already be a genuine Promise.
```js
// default fullfiled simply pass result along
// default rejected simply rethrow errors received
p.then( fulfilled );

p.then( fulfilled, rejected );

p.catch( rejected ); // or `p.then( null, rejected )`
```
`then(..) `takes one or two parameters, the first for the fulfillment callback, and the second for the rejection callback. If either is omitted or is otherwise passed as a non-function value, a default callback is substituted respectively. The default fulfillment callback simply passes the message along, while the default rejection callback simply rethrows (propagates) the error reason it receives.

`catch(..) `takes only the rejection callback as a parameter, and automatically substitutes the default fulfillment callback, as just discussed.

`then(..)` and `catch(..) `also create and return a new promise, which can be used to express Promise chain flow control. 
* If the fulfillment or rejection callbacks have an exception thrown, the returned promise is rejected. 
* If either callback returns an immediate, non-Promise, non-thenable value, that value is set as the fulfillment for the returned promise. 
* If the fulfillment handler specifically returns a promise or thenable value, that value is unwrapped and becomes the resolution of the returned promise.

The static helpers` Promise.all([ .. ])` and `Promise.race([ .. ])` on the ES6 Promise API both create a Promise as their return value. 

For` Promise.all([ .. ])`, all the promises you pass in must fulfill for the returned promise to fulfill. If any promise is rejected, the main returned promise is immediately rejected, too (discarding the results of any of the other promises). For fulfillment, you receive an array of all the passed in promises' fulfillment values. For rejection, you receive just the first promise rejection reason value. This pattern is classically called a "`gate`": all must arrive before the gate opens. **(fulfill: all the fulfill, reject: any reject)**

For `Promise.race([ .. ])`, only the first promise to resolve (fulfillment or rejection) "wins," and whatever that resolution is becomes the resolution of the returned promise. This pattern is classically called a "`latch`": first one to open the latch gets through. **(fulfill: any fullfil, reject: any reject)**

```js
var p1 = Promise.resolve( 42 );
var p2 = Promise.resolve( "Hello World" );
var p3 = Promise.reject( "Oops" );

Promise.race( [p1,p2,p3] )
.then( function(msg){
	console.log( msg );		// 42
} );

Promise.all( [p1,p2,p3] )
.catch( function(err){
	console.error( err );	// "Oops"
} );

Promise.all( [p1,p2] )
.then( function(msgs){
	console.log( msgs );	// [42,"Hello World"]
} );
```
**Warning**: Be careful! If an empty array is passed to Promise.all([ .. ]), it will fulfill immediately, but Promise.race([ .. ]) will hang forever and never resolve.
```js
var p = Promise.resolve( 42 );

p.then( something )//resource used
.finally( cleanup )// may comes in es7
.then( another )
.finally( cleanup );// clean up resource used
```

* `all([ .. ])`resolve when all of the input's promises have resolved, or if the input iterable contains no promises. It rejects immediately upon any of the input promises rejecting or non-promises throwing an error, and will reject with this first rejection message / error **(fulfill: all fulfill, reject: any reject)**
* `any([ .. ])` is like `all([ .. ])`, It returns a single promise that resolves as soon as any of the promises in the iterable fulfills, with the value of the fulfilled promise. If no promises in the iterable fulfill (if all of the given promises are rejected), then the returned promise is rejected with an AggregateError  **(fulfill: any fulfill, reject: all reject)**
* `race([ .. ])` fulfills or rejects as soon as one of the promises in an iterable fulfills or rejects **(fulfill: any fulfill, reject: any reject)**
* `allSettled([ .. ])`  resolves after all of the given promises have either fulfilled or rejected **(all have result: fullfil or reject)**

```js
// polyfill-safe guard check
// fulfill: any fulfill, reject: never
if (!Promise.first) {
	Promise.first = function(prs) {
		return new Promise( function(resolve,reject){
			// loop through all promises
			prs.forEach( function(pr){
				// normalize the value
				Promise.resolve( pr )
				// whichever one fulfills first wins, and
				// gets to resolve the main promise
				.then( resolve );
			} );
		} );
	};
}

```

let's consider an asynchronous map(..) utility that takes an array of values (could be Promises or anything else), plus a function (task) to perform against each. 

```js
if (!Promise.map) {
	Promise.map = function(vals,cb) {
		// new promise that waits for all mapped promises
		return Promise.all(
			// note: regular array `map(..)`, turns
			// the array of values into an array of
			// promises
			vals.map( function(val){
				// replace `val` with a new promise that
				// resolves after `val` is async mapped
				return new Promise( function(resolve){
					cb( val, resolve );
				} );
			} )
		);
	};
}


var p1 = Promise.resolve( 21 );
var p2 = Promise.resolve( 42 );
var p3 = Promise.reject( "Oops" );

// double values in list even if they're in
// Promises
Promise.map( [p1,p2,p3], function(pr,done){
	// make sure the item itself is a Promise
	Promise.resolve( pr )
	.then(
		// extract value as `v`
		function(v){
			// map fulfillment `v` to new value
			done( v * 2 );
		},
      // or, map to promise rejection message
      // we could do done(Promise.reject(Error('err'))) to reject.
      // here we only fulfill with the error passed in
		done
	);
} )
.then( function(vals){
	console.log( vals );	// [42,84,"Oops"]
} );

```
In this implementation of map(..), you can't signal async rejection, but if a synchronous exception/error occurs inside of the mapping callback (cb(..)), the main Promise.map(..) returned promise would reject.


### wraper
```js
function foo(x,y,cb) {
	ajax(
		"http://some.url.1/?x=" + x + "&y=" + y,
		cb
	);
}

foo( 11, 31, function(err,text) {
	if (err) {
		console.error( err );
	}
	else {
		console.log( text );
	}
} );

```
```js
// polyfill-safe guard check
if (!Promise.wrap) {
	Promise.wrap = function(fn) {
		return function() {
			var args = [].slice.call( arguments );

			return new Promise( function(resolve,reject){
				fn.apply(
					null,
					args.concat( function(err,v){
						if (err) {
							reject( err );
						}
						else {
							resolve( v );
						}
					} )
				);
			} );
		};
	};
}

var request = Promise.wrap( ajax );

request( "http://some.url.1/" )
.then( .. )
..
```
#### Unwrap/Spread Arguments
```js
function foo(bar,baz) {
	var x = bar * baz;

	// return both promises
	return [
		Promise.resolve( x ),
		getY( x )
	];
}

Promise.all(
	foo( 10, 20 )
)
.then( function(msgs){
	var x = msgs[0];
	var y = msgs[1];

	console.log( x, y );
} );
```

```js
// 1
function spread(fn) {
	return Function.apply.bind( fn, null );
}

Promise.all(
	foo( 10, 20 )
)
.then(
	spread( function(x,y){
		console.log( x, y );	// 200 599
	} )
)

//2
Promise.all(
	foo( 10, 20 )
)
.then( Function.apply.bind(
	function(x,y){
		console.log( x, y );	// 200 599
	},
	null
) );

//3
Promise.all(
	foo( 10, 20 )
)
.then( function(msgs){
	var [x,y] = msgs;

	console.log( x, y );	// 200 599
} );

//3
Promise.all(
	foo( 10, 20 )
)
.then( function([x,y]){
	console.log( x, y );	// 200 599
} );

```
https://github.com/getify/You-Dont-Know-JS/blob/master/async%20%26%20performance/ch3.md#single-resolution

